/* 
 * Sample Post Office API
 *
 * This is a sample post office API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing BeneficiariesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class BeneficiariesApiTests
    {
        private BeneficiariesApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new BeneficiariesApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BeneficiariesApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' BeneficiariesApi
            //Assert.IsInstanceOfType(typeof(BeneficiariesApi), instance, "instance is a BeneficiariesApi");
        }

        /// <summary>
        /// Test BeneficiariesGet
        /// </summary>
        [Test]
        public void BeneficiariesGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //instance.BeneficiariesGet();
            
        }
        /// <summary>
        /// Test BeneficiariesIdDelete
        /// </summary>
        [Test]
        public void BeneficiariesIdDeleteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //instance.BeneficiariesIdDelete(id);
            
        }
        /// <summary>
        /// Test BeneficiariesIdGet
        /// </summary>
        [Test]
        public void BeneficiariesIdGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //instance.BeneficiariesIdGet(id);
            
        }
        /// <summary>
        /// Test BeneficiariesPost
        /// </summary>
        [Test]
        public void BeneficiariesPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //instance.BeneficiariesPost();
            
        }
    }

}
