{
  "openapi" : "3.0.0",
  "info" : {
    "title" : "Product API",
    "description" : "",
    "version" : "1.0.1"
  },
  "servers" : [ {
    "url" : "/"
  } ],
  "paths" : { },
  "components" : { }
}